sudo: required
services:
  - docker

env:
  - CI=true

before_install:
  - docker build -t meghrathod/docker-react -f Dockerfile.dev .

script:
  - docker run meghrathod/docker-react npm run test -- --coverage